/** Operational QA gate catalog — mirrors docs/QA-GATE-RULES.md and boing-qa. */

export const QA_GATE_RULES_AS_OF = "26 August 2026";

export const HARD_RULES: {
  id: string;
  ruleId: string;
  title: string;
  outcome: "Reject";
  summary: string;
}[] = [
  {
    id: "R1",
    ruleId: "MALFORMED_BYTECODE",
    title: "Bytecode must not be empty",
    outcome: "Reject",
    summary: "bytecode.len() == 0 → “Bytecode must not be empty”.",
  },
  {
    id: "R2",
    ruleId: "MALFORMED_BYTECODE",
    title: "Init-code prefix must have a body",
    outcome: "Reject",
    summary:
      "Leading 0xFD (CONTRACT_DEPLOY_INIT_CODE_MARKER) with no following bytes is malformed. Opcode checks apply to bytes after the marker.",
  },
  {
    id: "R3",
    ruleId: "MAX_BYTECODE_SIZE",
    title: "Bytecode size cap",
    outcome: "Reject",
    summary: "Full payload (including optional 0xFD) must be ≤ registry max. Default 32,768 bytes (32 KiB).",
  },
  {
    id: "R4",
    ruleId: "INVALID_OPCODE",
    title: "Opcode whitelist",
    outcome: "Reject",
    summary: "Every instruction byte must be in the Boing VM table. PUSH immediates are data, not opcodes.",
  },
  {
    id: "R5",
    ruleId: "MALFORMED_BYTECODE",
    title: "Well-formed instruction stream",
    outcome: "Reject",
    summary:
      "PUSH1–PUSH32 must consume exactly 1–32 following bytes; the scan must end at len. Jump-target alignment is not checked at QA time.",
  },
  {
    id: "R6",
    ruleId: "BLOCKLIST_MATCH",
    title: "Bytecode hash blocklist",
    outcome: "Reject",
    summary: "BLAKE3-256 of the full payload must not match any registry.blocklist hash. Default list is empty.",
  },
  {
    id: "R7",
    ruleId: "PURPOSE_DECLARATION_INVALID",
    title: "Purpose category when provided",
    outcome: "Reject",
    summary:
      "If purpose is present and non-empty, it must be a valid category (case-insensitive). Missing purpose is allowed.",
  },
  {
    id: "R8",
    ruleId: "SCAM_PATTERN_MATCH",
    title: "Scam byte patterns",
    outcome: "Reject",
    summary: "Bytecode must not contain any registry.scam_patterns sequence as a contiguous window. Default list is empty.",
  },
  {
    id: "R9",
    ruleId: "METADATA_TOO_LONG",
    title: "Metadata length",
    outcome: "Reject",
    summary: "asset_name ≤ 256 UTF-8 bytes; asset_symbol ≤ 32 UTF-8 bytes (when those fields are sent).",
  },
  {
    id: "R10",
    ruleId: "CONTENT_POLICY_VIOLATION",
    title: "Content policy on name / symbol",
    outcome: "Reject",
    summary:
      "asset_name or asset_symbol must not match a content_blocklist term (see matching rules). Inert when the live list is empty.",
  },
];

export const SOFT_RULES: {
  id: string;
  title: string;
  outcome: "Unsure";
  summary: string;
}[] = [
  {
    id: "U1",
    title: "Always-review category",
    outcome: "Unsure",
    summary:
      "If the trimmed, lowercased purpose is in registry.always_review_categories, the deploy goes to the pool. Default list is empty.",
  },
  {
    id: "U2",
    title: "other with almost no description",
    outcome: "Unsure",
    summary:
      "Purpose other plus description_hash shorter than 4 bytes (missing counts as 0) goes to the pool. other with ≥ 4-byte hash can Allow.",
  },
];

export const VALID_PURPOSE_CATEGORIES = [
  "dApp / dapp",
  "token",
  "NFT / nft",
  "meme",
  "community",
  "entertainment",
  "tooling",
  "other",
] as const;

export const OPCODES: { byte: string; name: string }[] = [
  { byte: "0x00", name: "STOP" },
  { byte: "0x01", name: "ADD" },
  { byte: "0x02", name: "SUB" },
  { byte: "0x03", name: "MUL" },
  { byte: "0x04", name: "DIV" },
  { byte: "0x06", name: "MOD" },
  { byte: "0x08", name: "ADDMOD" },
  { byte: "0x09", name: "MULMOD" },
  { byte: "0x10", name: "LT" },
  { byte: "0x11", name: "GT" },
  { byte: "0x14", name: "EQ" },
  { byte: "0x15", name: "ISZERO" },
  { byte: "0x16", name: "AND" },
  { byte: "0x17", name: "OR" },
  { byte: "0x18", name: "XOR" },
  { byte: "0x19", name: "NOT" },
  { byte: "0x1B", name: "SHL" },
  { byte: "0x1C", name: "SHR" },
  { byte: "0x1D", name: "SAR" },
  { byte: "0x30", name: "ADDRESS" },
  { byte: "0x33", name: "CALLER" },
  { byte: "0x40", name: "BLOCKHEIGHT" },
  { byte: "0x41", name: "TIMESTAMP" },
  { byte: "0x51", name: "MLOAD" },
  { byte: "0x52", name: "MSTORE" },
  { byte: "0x54", name: "SLOAD" },
  { byte: "0x55", name: "SSTORE" },
  { byte: "0x56", name: "JUMP" },
  { byte: "0x57", name: "JUMPI" },
  { byte: "0x60–0x7F", name: "PUSH1–PUSH32" },
  { byte: "0x80", name: "DUP1" },
  { byte: "0xA0–0xA4", name: "LOG0–LOG4" },
  { byte: "0xF1", name: "CALL" },
  { byte: "0xF3", name: "RETURN" },
  { byte: "0xF5", name: "CREATE2" },
];

export const EVALUATION_STEPS = [
  "METADATA_TOO_LONG — name > 256 or symbol > 32 UTF-8 bytes",
  "Empty bytecode → MALFORMED_BYTECODE",
  "Init marker 0xFD with no body → MALFORMED_BYTECODE",
  "MAX_BYTECODE_SIZE (default 32,768)",
  "INVALID_OPCODE or MALFORMED_BYTECODE on the stream after optional 0xFD",
  "BLOCKLIST_MATCH — BLAKE3 of the full payload",
  "PURPOSE_DECLARATION_INVALID — non-empty purpose not in the valid set",
  "SCAM_PATTERN_MATCH — contiguous byte sequence",
  "CONTENT_POLICY_VIOLATION — name/symbol vs content_blocklist",
  "Always-review category → Unsure",
  "other with description_hash shorter than 4 bytes → Unsure",
  "Allow",
] as const;

export const RPC_QA_ERRORS: { code: string; summary: string }[] = [
  { code: "-32050", summary: "Rejected by protocol QA (rule_id + message)." },
  { code: "-32051", summary: "Unsure — referred to the governance QA pool (pending tx_hash)." },
  { code: "-32052", summary: "No pending pool item for that transaction hash." },
  { code: "-32053", summary: "Voter ineligible (not a member, deployer conflict, or stake)." },
  { code: "-32054", summary: "QA pool disabled (no admins / zero capacity)." },
  { code: "-32055", summary: "Global pool capacity reached." },
  { code: "-32056", summary: "Per-deployer pending cap reached." },
  { code: "-32057", summary: "Operator RPC auth required (X-Boing-Operator)." },
];

export const CONTENT_BLOCKLIST_TERMS: readonly string[] = [
  "a55hole",
  "asshole",
  "assholes",
  "b1tch",
  "badass",
  "bastard",
  "bastards",
  "beaner",
  "beaners",
  "bestiality",
  "bitch",
  "bitches",
  "bitchy",
  "blowjob",
  "bollocks",
  "bukkake",
  "bullshit",
  "child porn",
  "childporn",
  "chink",
  "chinks",
  "clitoris",
  "cocksucker",
  "cocksuckers",
  "cunt",
  "cunts",
  "dilf",
  "dipshit",
  "douche",
  "douchebag",
  "douchebags",
  "dumbass",
  "dyke",
  "dykes",
  "ejaculate",
  "ejaculation",
  "faggot",
  "faggots",
  "fagot",
  "fck",
  "fuck",
  "fucked",
  "fucker",
  "fuckers",
  "fuckface",
  "fuckhead",
  "fucking",
  "fuckwit",
  "fuk",
  "fvck",
  "gangbang",
  "go die",
  "gook",
  "gooks",
  "handjob",
  "heil",
  "hentai",
  "hitler",
  "jackass",
  "kike",
  "kikes",
  "kill yourself",
  "kys",
  "masturbate",
  "masturbation",
  "mfucker",
  "milf",
  "motherfucker",
  "motherfuckers",
  "nazi",
  "nazis",
  "nigga",
  "niggas",
  "nigger",
  "niggers",
  "onlyfans",
  "orgasm",
  "paedophile",
  "paedophilia",
  "pedophile",
  "pedophilia",
  "penis",
  "penises",
  "phuck",
  "porn",
  "pornhub",
  "porno",
  "pornography",
  "pussies",
  "pussy",
  "raghead",
  "retard",
  "retardation",
  "retarded",
  "rimjob",
  "sandnigger",
  "scrotum",
  "sh1t",
  "shit",
  "shitbag",
  "shitface",
  "shithead",
  "shits",
  "shitshow",
  "shitty",
  "slut",
  "sluts",
  "slutty",
  "spic",
  "spics",
  "swastika",
  "testicle",
  "testicles",
  "towelhead",
  "trannies",
  "tranny",
  "twat",
  "twats",
  "vagina",
  "vaginas",
  "vulva",
  "wanker",
  "wankers",
  "wetback",
  "wetbacks",
  "whitepower",
  "whore",
  "whores",
  "whoring",
  "xvideos",
  "xxx",
  "zoophilia",
];
